.Dd January 31, 2014
.Dt evtinfo
.Os libevt
.Sh NAME
.Nm evtinfo
.Nd determines information about a Windows Event Log (EVT)
.Sh SYNOPSIS
.Nm evtinfo
.Op Fl c Ar codepage
.Op Fl hvV
.Va Ar source
.Sh DESCRIPTION
.Nm evtinfo
is a utility to determine information about a Windows Event Log (EVT)
.Pp
.Nm evtinfo
is part of the
.Nm libevt
package.
.Nm libevt
is a library to access the Windows Event Log (EVT) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar codepage
specify the codepage of ASCII strings, options: ascii, windows-874, windows-932, windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252 (default), windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 or windows-1258
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# evtinfo AppEvent.Evt
evtinfo 20120624

Windows Event Log (EVT) information:
	Version				: 1.1
	Number of records		: 19
	Number of recovered records	: 0
	Log type			: Application
	Flags:
		Should be archived

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libevt/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2011-2018, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr evtexport 1
